baseURL = "https://rongsun-ac.github.io/"
title = "Rong Sun"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
disableLanguages = []

[params]
  browserTitle = "Rong Sun"
  labShortName = "Rong Sun"
  labName = "Academic Profile"
  logo = "images/members/aiclab_member_default.png"
  favicon = "favicon-rongsun-32x32.png"
  faviconIco = "favicon-rongsun-32x32.png"
  appleTouchIcon = "apple-touch-icon-rongsun.png"
  description = "Academic website of Rong Sun"
  showCitations = true
  showVisitCounter = true

[params.visibility]
  disabledLanguages = []
  disabledSections = ["research", "projects", "news", "members", "access", "links"]

[markup.goldmark.renderer]
  unsafe = true

[languages.en]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1
  title = "Rong Sun"
  [languages.en.params]
    labName = "Academic Profile"
    labShortName = "Rong Sun"

[[languages.en.menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10
[[languages.en.menu.main]]
  name = "Publications"
  pageRef = "/publications"
  weight = 20

[languages.ja]
  languageName = "日本語"
  languageCode = "ja-jp"
  contentDir = "content/ja"
  weight = 2
  title = "Rong Sun"
  [languages.ja.params]
    labName = "Academic Profile"
    labShortName = "Rong Sun"

[[languages.ja.menu.main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10
[[languages.ja.menu.main]]
  name = "文献リスト"
  pageRef = "/publications"
  weight = 20

[languages.zh]
  languageName = "中文"
  languageCode = "zh-cn"
  contentDir = "content/zh"
  weight = 3
  title = "Rong Sun"
  [languages.zh.params]
    labName = "Academic Profile"
    labShortName = "Rong Sun"

[[languages.zh.menu.main]]
  name = "首页"
  pageRef = "/"
  weight = 10
[[languages.zh.menu.main]]
  name = "研究业绩"
  pageRef = "/publications"
  weight = 20
